--AUTOR CONSULTOR TOTVS ARIONE.JUNIOR@TOTVS.COM.BR
--FRANKENSTEIN
--ROTINA 105
--ERP WINTHOR

SELECT ROUND(SUM(VLCUSTOREAL),2) AS valor FROM (
SELECT 
       SUM(NVL(NVL(PCEST2.QTESTGER,0) - NVL(PCEST2.QTRESERV,0) - NVL(PCEST2.QTBLOQUEADA,0) -  (CASE WHEN (SELECT  NVL (PARAMFILIAL.OBTERCOMOVARCHAR2 ('BLOQUEIAVENDAESTPENDENTE',
                  PCFILIAL.CODIGO), PCCONSUM.BLOQUEIAVENDAESTPENDENTE)
                BLOQUEIAVENDAESTPENDENTE
  FROM  PCFILIAL, PCCONSUM
 WHERE  CODIGO <> '99' AND CODIGO IN ('1') AND DTEXCLUSAO IS NULL
) = 'S' THEN  NVL(PCEST2.QTPENDENTE, 0)  ELSE 0 END) ,0) * NVL(PCEST2.CUSTOREAL,0)) VLCUSTOREAL 
FROM PCPRODUT, 
       PCEST PCEST2, 
       PCFORNEC, 
       PCMARCA, 
       PCLINHAPROD, 
       PCDEPTO, 
       PCSECAO, 
       PCCONSUM 
 WHERE PCPRODUT.CODPROD  = PCEST2.CODPROD 
   AND PCPRODUT.CODMARCA = PCMARCA.CODMARCA(+) 
   AND PCPRODUT.CODLINHAPROD = PCLINHAPROD.CODLINHA(+) 
   --AND PARAMETROS.CODIGO = PCEST2.CODFILIAL 
 AND PCPRODUT.DTEXCLUSAO IS NULL 
   AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO                                                       
   AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)                                                      
   AND NVL(PCDEPTO.TIPOMERC, 'XX') NOT IN ('IM','CI')                                     
   AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC 
   AND PCEST2.CODFILIAL IN ('1')                                                 
 HAVING SUM((NVL(PCEST2.QTESTGER,0) - NVL(PCEST2.QTRESERV,0) - NVL(PCEST2.QTBLOQUEADA,0) -  (CASE WHEN (SELECT  NVL (PARAMFILIAL.OBTERCOMOVARCHAR2 ('BLOQUEIAVENDAESTPENDENTE',
                  PCFILIAL.CODIGO), PCCONSUM.BLOQUEIAVENDAESTPENDENTE)
                BLOQUEIAVENDAESTPENDENTE
  FROM  PCFILIAL, PCCONSUM
 WHERE  CODIGO <> '99' AND CODIGO IN ('1') AND DTEXCLUSAO IS NULL
) = 'S' THEN  NVL(PCEST2.QTPENDENTE, 0)  ELSE 0 END) )) > 0 
 GROUP BY --ADDGROUPFILIAL 
          --PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
          --PARAMETROS.PRECOPOREMBALAGEM, 
          PCPRODUT.CODPROD, 
          NVL(PCPRODUT.DESCRICAO,''), 
          PCPRODUT.NUMORIGINAL, 
          NVL(PCPRODUT.EMBALAGEM, ''), 
          PCPRODUT.CODEPTO, 
          PCDEPTO.DESCRICAO, 
          PCPRODUT.CODSEC, 
          PCPRODUT.OBS2, 
          PCSECAO.DESCRICAO, 
          PCPRODUT.CODFORNEC, 
          PCFORNEC.FORNECEDOR, 
          PCFORNEC.FANTASIA, 
          PCFORNEC.CODFORNECPRINC, 
          PCPRODUT.CODFAB, 
          PCPRODUT.QTUNITCX, 
          NVL(PCMARCA.MARCA,''), 
          PCLINHAPROD.DESCRICAO, 
          PCPRODUT.CODMARCA, 
          PCPRODUT.CODLINHAPROD, 
          PCPRODUT.CLASSE, 
          PCPRODUT.CLASSEVENDA, 
          PCPRODUT.NBM)


